# Generated by Django 6.0.1 on 2026-02-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
