# Generated by Django 6.0.1 on 2026-03-02 08:24

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_profile_recipe_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['name'], 'verbose_name': 'recipe', 'verbose_name_plural': 'books'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='updatedOn',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shortBio',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(255, 'The field must contain at least 255 characters!')]),
        ),
    ]
